elasticsearch_node1:
  build: elasticsearch/
  ports:
    - "9200:9200"
elasticsearch_node2:
  build: elasticsearch/
  ports:
    - "9201:9201"
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - logstash-conf:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  links:
    - elasticsearch
kibana:
  build: kibana/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
